version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: circleci/node:18
        environment:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: 'nestjs_db'
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run migrations
          command: yarn prisma migrate deploy
      - run:
          name: Run tests
          command: yarn test
